[package]
name = "sketchlib"
version = "0.1.0"
authors = [
    "John Lees <jlees@ebi.ac.uk>",
    "Nicholas Croucher <n.croucher@imperial.ac.uk>"
]
edition = "2021"
description = "Genome and amino-acid sketching"
repository = "https://github.com/bacpop/sketchlib.rust"
homepage = "https://bacpop.org/software/"
license = "Apache-2.0"
readme = "README.md"
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/NOTICE",
    "/src",
    "/tests"
]
keywords = ["bioinformatics", "genomics", "sequencing", "k-mer", "sketch"]
categories = ["command-line-utilities", "science"]

[dependencies]
# i/o
needletail = { version = "0.5", features = ["compression"] }
hdf5 = "0.8"
hdf5-sys = { version = "*", features = ["static"] }
ska = "0.3.6"
# logging
log = "0.4"
simple_logger = { version = "4", features = ["stderr"] }
indicatif = { version = "0.17", features = ["rayon"]}
# cli
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
# parallelisation
rayon = "1.8"
num_cpus = "1.0"

[dev-dependencies]
# testing
snapbox = "0.4.3"
predicates = "2.1.5"
assert_fs = "1.0.10"
pretty_assertions = "1.3.0"
