name: Cargo Build & Test on Windows

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --verbose
      - run: cargo test --verbose
